### PR TITLE
connect: fix reference error in  `mapDispatchToProps`

### LINKED ISSUE #4: connect.js:128 Uncaught ReferenceError: stateProps is not defined
when accessing `ownProps` from within `mapDispatchToProps`, deku-redux throws a ReferenceError

smallest test case i could create:

``` js

import element from 'virtual-element'
import { tree, render } from 'deku'
import { createStore } from 'redux'
import { connect, storePlugin } from 'deku-redux'

const App = connect(mapStateToProps, mapDispatchToProps)({
  render () {
    return <div />
  },
  afterMount ({ props }) {
    props.something()
  }
})

function mapStateToProps (state, ownProps) {
  return {}
}

function mapDispatchToProps (dispatch, ownProps) {
  return {
    something: () => dispatch({ type: 'DID_SOMETHING' })
  }
}

const reducer = (state = {}, action) => state
const store = createStore(reducer)

const app = tree(<App foo='bar' />)
app.use(storePlugin(store))
render(app, document.getElementById('root'))
```

strangely enough, this works fine though:

``` js
function mapDispatchToProps (dispatch /*, ownProps*/) {
  const ownProps = arguments[1]
  return {
    something: () => dispatch({ type: 'DID_SOMETHING' })
  }
}
```

### PR DESCRIPTION
**Pull request by stephenmathieson**
closes #4

### CODE REVIEW

**Comment by stephenmathieson** [comment]
travis is failing for super unrelated reasons...

**Comment by troch** [comment]
Thanks, I'm merging it just now, will investigate why CI is failing and then release.

**Comment by troch** [comment]
`1.1.1` released

**Comment by stephenmathieson** [comment]
thanks dude!

**Pull request merged**
